services:
  ciallo-proxy:
    image: ghcr.io/murasamecyan/ciallo-ms-365-openai-proxy-docker:latest
    container_name: ciallo-ms365-proxy
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - chrome-profile:/chrome-profile
    environment:
      - AUTO_REFRESH=true
      - REFRESH_BEFORE_SECONDS=300
      - CHROME_CDP_PORT=9222
    restart: unless-stopped
    shm_size: "1gb"

volumes:
  chrome-profile:
